### ISSUE TITLE
有对pulumi的provider计划吗

### ISSUE THREAD

**Issue by DomineCore** [tencentcloudstack/terraform-provider-tencentcloud#1133]

**Comment by Kagashino** [comment]
Hi @DomineCore 
有计划支持的，但目前还处于论证阶段，暂时还无法同步具体的细节

**Comment by Kagashino** [comment]
Hi @DomineCore 
Pulumi TencentCloud 现已有可试用的版本 https://github.com/tencentcloudstack/pulumi-tencentcloud
