### ISSUE TITLE
`tencentcloud_tem_gateway`: certificate can not be updated

### ISSUE THREAD

**Issue by smorimoto** [tencentcloudstack/terraform-provider-tencentcloud#1648]
There is a bug that even if you update the ID of a certificate, the certificate will not actually be updated even if Terraform says successfully updated. Even if you manually update, it will revert to the old ID during the next apply process, so it's very annoying.

**Comment by hellertang** [comment]
@gitmkn

**Comment by gitmkn** [comment]
好的，这个问题确认后尽快处理

**Comment by gitmkn** [comment]
好的，这个问题确认后尽快处理
Ok, this problem will be dealt with as soon as possible after confirmation

**Comment by smorimoto** [comment]
我认为它将帮助许多用户。谢谢 🙂

**Comment by smorimoto** [comment]
Fixed in https://github.com/tencentcloudstack/terraform-provider-tencentcloud/pull/1672.
