### ISSUE TITLE
使用terraform官网的registry，tencentcloud_vpc例子写错了一个参数

### ISSUE THREAD

**Issue by q48775533q** [tencentcloudstack/terraform-provider-tencentcloud#1696]
以下为terraform的registry上的例子。
resource "tencentcloud_vpc" "foo" {
  name           = "ci-temp-test-updated"
  cidr_block     = "10.0.0.0/16"
  is_multicast   = false
  assistant_cidr = ["172.16.0.0/24"]   <-------- 此处少了个s   应该是assistant_cidrs

  tags = {
    "test" = "test"
  }
}

**Comment by andrew-tx** [comment]
谢谢反馈，该问题在新版本中已经修复
