### ISSUE TITLE
Bug in documentation for TKE kubernetes_node_pool resource

### ISSUE THREAD

**Issue by AlexCQY** [tencentcloudstack/terraform-provider-tencentcloud#2085]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

tencentcloud provider version: `1.81.22`

### Affected Resource(s)

* tencentcloud_kubernetes_node_pool

### Debug Output

![image](https://github.com/tencentcloudstack/terraform-provider-tencentcloud/assets/59348559/e3c57097-1678-4594-b48d-89dc50f325fb)
![tf_ss](https://github.com/tencentcloudstack/terraform-provider-tencentcloud/assets/59348559/9dbe1f67-2f44-4c68-91c3-70309469605e)
![tf_ss_2](https://github.com/tencentcloudstack/terraform-provider-tencentcloud/assets/59348559/97d0c59f-25c5-4f4d-8796-a880ebdcebc4)

### References

* https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/kubernetes_node_pool#internet_charge_type

**Comment by andrew-tx** [comment]
新版本已经修复文档问题
