### ISSUE TITLE
Invalid mem_size in tencentcloud_redis_instance

### ISSUE THREAD

**Issue by maolilong1988** [tencentcloudstack/terraform-provider-tencentcloud#2453]
### Tencent Provider Version

1.81.62

### Terraform Version

1.6.3

### Affected Resource(s)

tencentcloud_redis_instance

### Panic Output

![image](https://github.com/tencentcloudstack/terraform-provider-tencentcloud/assets/41989056/6e71af33-8286-4b5f-8885-e69600b63c69)

### Comment

I was using the provider version 1.81.45, which everything worked fine.

After upgrading to 1.81.62, I got the issue as the screenshot above. 

I found the team had added mem_size value check in 1.81.46 and 256 is not a valid value. While actually my redis resource is 256MB mem_size and this made me can't use terraform to manage the resources.

![image](https://github.com/tencentcloudstack/terraform-provider-tencentcloud/assets/41989056/e6a0b9c3-6c0c-4188-9d0a-ff50e54d100a)

Is there any plan to add 256 as the valid mem_size value?

**Comment by andrew-tx** [comment]
新版本已修复
