### ISSUE TITLE
After updating to 1.81.70, TencentCloud returns SDKError

### ISSUE THREAD

**Issue by lostchai** [tencentcloudstack/terraform-provider-tencentcloud#2501]
{
    "Response": {
        "Error": {
            "Code": "InvalidParameterValue",
            "Message": "The value `[]` specified in the parameter `Filters` is not valid."
        },
        "RequestId": "32e2394e-0c01-4dff-bf98-fe308fd24cca"
    }
}
 in resource "tencentcloud_clb_target_group" "group"

**Comment by andrew-tx** [comment]
升级腾讯云 SDK 引入该问题，已经在新版本中修复
