### ISSUE TITLE
支持修改更新 TKE eniipamd 组件的全局配置

### ISSUE THREAD

**Issue by lancelot1989** [tencentcloudstack/terraform-provider-tencentcloud#2579]
https://docs.qq.com/doc/DY3lEV21aVmxGZU9J

比如TKE的这个功能，需要更新 eniipamd 组件的全部配置，希望provider能提供对应的能力

**Comment by lyu571** [comment]
该组件需要待新的addon资源上线。资源接入tf需要一定的时间和流程，待该资源上线后我们及时通知您。

**Comment by andrew-tx** [comment]
该功能在 1.81.93 版本中已经支持：
https://github.com/tencentcloudstack/terraform-provider-tencentcloud/releases/tag/v1.81.93
