### ISSUE TITLE
TKE添加节点或者节点池，支持自定义脚本功能

### ISSUE THREAD

**Issue by lancelot1989** [tencentcloudstack/terraform-provider-tencentcloud#2580]
<img width="792" alt="image" src="https://github.com/tencentcloudstack/terraform-provider-tencentcloud/assets/13790518/9e0be51c-7cb2-41dc-9b0d-dda9384820bb">

**Comment by andrew-tx** [comment]
已在新版本支持：https://github.com/tencentcloudstack/terraform-provider-tencentcloud/releases/tag/v1.81.98
