### ISSUE TITLE
Can we support user-data for tencentcloud_kubernetes_cluster_attachment?

### ISSUE THREAD

**Issue by deancn** [tencentcloudstack/terraform-provider-tencentcloud#411]
### Description

When I use tencentcloud_kubernetes_cluster_attachment,  the attached servers are re-installed. So I think it is better if supporting user-data (like worker_config user-data) for automatic. 

The user-data function already for new servers in worker_config.

### New or Affected Resource(s)

* tencentcloud_kubernetes_cluster_attachment

**Comment by deancn** [comment]
can add user_data to  resourceTencentCloudTkeClusterAttachmentCreate
https://github.com/terraform-providers/terraform-provider-tencentcloud/blob/master/tencentcloud/resource_tc_kubernetes_cluster_attachment.go#L264


user_data Refere:  
https://github.com/terraform-providers/terraform-provider-tencentcloud/blob/master/tencentcloud/resource_tc_kubernetes_cluster.go#L780

**Comment by likexian** [comment]
Hello @deancn 
We will look into this issue and reply here assp.

**Comment by deancn** [comment]
@likexian  Thanks for your response.  Not urgent.

**Comment by likexian** [comment]
Hello @deancn 
Since this is not supported by our openAPI, it may take a longer time to finish.
When it is ready, I will reply here, sorry for the delay.

**Comment by likexian** [comment]
Hello @deancn 
user_data is now supported, please upgrade to the latest version and have a try.
refer: https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/kubernetes_cluster_attachment#user_data

**Comment by deancn** [comment]
thanks.

**Comment by deancn** [comment]
```
resource "tencentcloud_kubernetes_cluster_attachment" "test_attach" {
  cluster_id  = tencentcloud_kubernetes_cluster.managed_cluster.id
  instance_id = tencentcloud_instance.foo.id
  password    = "Lo4wbdit"

  labels = {
    "test1" = "test1",
    "test2" = "test2",
  }
}
```

Hi  @likexian 
user-data should be here. Not in worker_config config.

**Comment by likexian** [comment]
Yes, there is user_data in worker_config.

Is it work for you?

**Comment by deancn** [comment]
```
resource "tencentcloud_kubernetes_cluster" "managed_cluster" {
  cluster_version         = "1.16.3"
  vpc_id                  = var.vpc
  cluster_cidr            = "172.16.0.0/24"
  cluster_max_pod_num     = 32
  cluster_name            = "kube-xx"
  cluster_desc            = "test cluster desc"
  cluster_max_service_num = 32


  worker_config {
    count                      = 1
    availability_zone          = var.availability_zone
    instance_type              = var.default_instance_type
    public_ip_assigned         = true
    subnet_id                  = var.subnet

    user_data                 = "IyEvYmluL2Jhc2gKCmN1cmwgaHR0cHM6Ly9pbml0LmFpcmRiLmhvc3Qvb3Npbml0L3VidW50dV9pbml0LnNoIHwgYmFzaCAt"
  }

  cluster_deploy_type = "MANAGED_CLUSTER"

  tags = {
    "test" = "test"
  }

}


resource "tencentcloud_kubernetes_cluster_attachment" "test_attach" {
cluster_id  = tencentcloud_kubernetes_cluster.managed_cluster.id
  instance_id = "ins-xx"
key_ids = ["skey-xx"]
}

````

It doesn't work.    what I need is attach an existing instance to the cluster. 
But actually, will attach the instance and create a new instance.    that's mean the cluster will have 2 cvm instances.

**Comment by likexian** [comment]
Hello @deancn 
Please have a try this:

```
resource "tencentcloud_kubernetes_cluster_attachment" "test_attach" {
  cluster_id  = tencentcloud_kubernetes_cluster.managed_cluster.id
  instance_id = "ins-xx"
  key_ids = ["skey-xx"]

  worker_config {
    user_data = "IyEvYmluL2Jhc2gKCmN1cmwgaHR0cHM6Ly9pbml0LmFpcmRiLmhvc3Qvb3Npbml0L3VidW50dV9pbml0LnNoIHwgYmFzaCAt"
  }
}
```

**Comment by deancn** [comment]
Hi Like,
thank you.  it works.

**Comment by likexian** [comment]
> Hi Like,
> thank you. it works.

you are welcome.
