### ISSUE TITLE
tencentcloud_ccn_bandwidth_limit  go Error: [TencentCloudSDKError] Code=UnsupportedOperation, Message=Unsupported operation

### ISSUE THREAD

**Issue by hanyouqing** [tencentcloudstack/terraform-provider-tencentcloud#484]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

I'm going to create `CNN` for 2 different `VPCs` in Beijing and Silicon Valley. 

The `VPCs`, `CVMs` and `CCN` are done, but block by bandwith of `CCN`, see details below: 

```sh
$ terraform version
Terraform v0.12.25
+ provider.aws v2.70.0
+ provider.tencentcloud v1.40.0

Your version of Terraform is out of date! The latest version
is 0.12.29. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

```hcl
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # tencentcloud_ccn_bandwidth_limit.bj2ussv-cnn-limit will be created
  + resource "tencentcloud_ccn_bandwidth_limit" "bj2ussv-cnn-limit" {
      + bandwidth_limit = 1
      + ccn_id          = "ccn-obflh40d"
      + id              = (known after apply)
      + region          = "ap-beijing"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
```

### Terraform Configuration Files

```hcl
resource "tencentcloud_ccn_bandwidth_limit" "bj2ussv-cnn-limit" {
  ccn_id          = tencentcloud_ccn.bj2ussv-cnn.id
  region          = var.ccn_vpc.beijing.region
  bandwidth_limit = 1
}
```

### Debug Output

```
tencentcloud_instance.ccn-bj-inst[0]: Refreshing state... [id=ins-h8lauwcj]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # tencentcloud_ccn_bandwidth_limit.bj2ussv-cnn-limit will be created
  + resource "tencentcloud_ccn_bandwidth_limit" "bj2ussv-cnn-limit" {
      + bandwidth_limit = 1
      + ccn_id          = "ccn-obflh40d"
      + id              = (known after apply)
      + region          = "ap-beijing"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

tencentcloud_ccn_bandwidth_limit.bj2ussv-cnn-limit: Creating...

Error: [TencentCloudSDKError] Code=UnsupportedOperation, Message=Unsupported operation., RequestId=a023eeda-207e-4b25-8b4a-a511a0673c2a

  on ccn.tf line 15, in resource "tencentcloud_ccn_bandwidth_limit" "bj2ussv-cnn-limit":
  15: resource "tencentcloud_ccn_bandwidth_limit" "bj2ussv-cnn-limit" {


Releasing state lock. This may take a few moments...
```

### Addtional Quesitons

Besides the error I mentioned, there are also some questions, it'll be appreciated if anybody can tell me about that.

1. Is `tencentcloud_ccn_bandwidth_limit` the same thing with `带宽管理`  on the web console?
2. If question 1 is true, there's should be 2 region for `tencentcloud_ccn_bandwidth_limit`,   while just 1 `region` paramater for `tencentcloud_ccn_bandwidth_limit` on the [docs](https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/ccn_bandwidth_limit#id) 
3. What's the unit of `bandwidth_limit`? (maybe `Mbps`, i don't know)
4. I can not find a paramater for `auto-renew` for ccn relationed resources on the docs, what should i do if i need it.

**Comment by hanyouqing** [comment]
Thank the replied by [Sai Zhang](1277030291@qq.com) about that:

Answer for Q3:  The unit of `bandwidth_limit` is _Mbps_.
Answer for Q4: `Tencent Terraform Plugins` just support paid by traffic for now, which means it's not supported yet.

**Comment by hanyouqing** [comment]
Anyone who can help? (Sorry to trouble, just want to find the answer from the specialists as you guys on [cnn](https://github.com/tencentcloudstack/terraform-provider-tencentcloud/blame/2d46f19244d459fe2115a217510dbfbd24075ca4/tencentcloud/resource_tc_ccn_bandwidth_limit.go) )
@Himer @likexian @lazzurs @JihaoXin @oliverpei

**Comment by brickzzhang** [comment]
Hello, hanyouqing, sorry for you to encounter this issue.

**Comment by brickzzhang** [comment]
hello, hanyouqing. sorry for you to encounter this issue. here are my opinions about your questions as i checked source codes.

Answer for Q1: actually `tencentcloud_ccn_bandwidth_limit` is a part of `带宽管理` on console. There are 2 kinds of bandwidth managements, one is inter-region and another one is between regions. And the 2nd one is not supported yet.
![image](https://user-images.githubusercontent.com/7894225/89152095-f6c1e600-d594-11ea-89a3-5d124f26c052.png)
And answer for Q2 is also clear.

For the issue you encountered, will try to reproduct it and reply to you asap.

**Comment by brickzzhang** [comment]
hello, hanyouqing. As we checked the log according to the req id, your ccn instance is in prepaid type which doesn't support bandwidth limitation setting.

**Comment by hanyouqing** [comment]
> hello, hanyouqing. As we checked the log according to the req id, your ccn instance is in prepaid type which doesn't support bandwidth limitation setting.

Thanks a lot!  
I'm soory for miss something else:  i've imported the exists ccn instance which was `prepaid`.
I tried to remove it from the state and recreate it as it was said that the default instance created by `terraform tecentcloud plugin` is `postpaid`, but **got the same error as previsous**.

**Comment by hanyouqing** [comment]
> hello, hanyouqing. sorry for you to encounter this issue. here are my opinions about your questions as i checked source codes.
> 
> Answer for Q1: actually `tencentcloud_ccn_bandwidth_limit` is a part of `带宽管理` on console. There are 2 kinds of bandwidth managements, one is inter-region and another one is between regions. And the 2nd one is not supported yet.
> ![image](https://user-images.githubusercontent.com/7894225/89152095-f6c1e600-d594-11ea-89a3-5d124f26c052.png)
> And answer for Q2 is also clear.
> 
> For the issue you encountered, will try to reproduct it and reply to you asap.

Thanks for syncing, the feature of 2nd one is really useful for a production environment, expecting.

**Comment by hanyouqing** [comment]
Finally got fixed, will close this issue with whilte the details of the problem and solution commented here.

Thank @brickzzhang and some LeiFeng engineers working on this project.

**Comment by hanyouqing** [comment]
This is not a bug, just something mis-configration of the backend of tencent cloud.
