### ISSUE TITLE
What should I do if I wish to decrease the number of instance in a K8S cluster

### ISSUE THREAD

**Issue by jichaofdu** [tencentcloudstack/terraform-provider-tencentcloud#497]
[terraform-provider-tencentcloud/tencentcloud/resource_tc_kubernetes_scale_worker.go](https://github.com/tencentcloudstack/terraform-provider-tencentcloud/blob/master/tencentcloud/resource_tc_kubernetes_scale_worker.go)

From the code above we know that we could increase the number of workers in a K8S cluster by using Resource "tencentcloud_kubernetes_scale_worker".

But what should I do if I wish to decrease the number of instance in a K8S cluster ?

thx !

**Comment by Himer** [comment]
The `tencentcloud_kubernetes_scale_worker` does not support deleting one or more servers, only all of them. The following two methods can be used to delete nodes
1. Use `tencentcloud_instance` and `tencentcloud_kubernetes_cluster_attachment` to handle
2. Use more than one `tencentcloud_kubernetes_scale_worker`for capacity expansion, and then delete one `tencentcloud_kubernetes_scale_worker`
