### ISSUE TITLE
Attribute private_ip of tencentcloud_instance is expected.

### ISSUE THREAD

**Issue by hanyouqing** [tencentcloudstack/terraform-provider-tencentcloud#509]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For example, for some internal security reasons, i want set host specific security_group rules which needs the private_ips.

### New or Affected Resource(s)

* tencentcloud_instance

### Potential Terraform Configuration

```
source = tencentcloud_instance.XXX-DB.private_ip
```

**Comment by oliverpei** [comment]
Hi @hanyouqing ,
private_ip of tencentcloud_instance is supported, please refer to the [document](https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/instance#private_ip).

**Comment by hanyouqing** [comment]
Yes verified, thank you!
maybe something wrong with my code, i think I have fixed it and forget to close this issue. Sorry about that.
