### ISSUE TITLE
tencentcloud_clb_listener_rule missing backend protocols argument

### ISSUE THREAD

**Issue by Teakowa** [tencentcloudstack/terraform-provider-tencentcloud#522]
`tencentcloud_clb_listener_rule` missing backend protocols (后端协议) argument, it is set to HTTP by default.

If HTTP redirection to HTTPS is configured on the backend server, this causes a 302 loop redirect when both listener and backend protocols are HTTPS.

Anyway, the argument should be configurable.

**Comment by gailwang** [comment]
This feature has been supported in version 1.45.0
