### ISSUE TITLE
tencentcloud_cdn_domain add support for (Cross-border) Origin Pull Optimization

### ISSUE THREAD

**Issue by jossy** [tencentcloudstack/terraform-provider-tencentcloud#542]
When using a backend outside of China it seems to be essential for performance to make use of the (Cross-border) Origin Pull Optimization (for `mainland` area distribution). If switched on, the configuration (according to the API Explorer) features these settings:

```
"OriginPullOptimization": {
  "Switch": "on",
  "OptimizationType": "CNToOV"
},
```
Apparently, the default value of this setting differs between accounts.
To ensure the state of this setting, would it be possible to support it in the Terraform provider?

**Comment by gailwang** [comment]
Hi, @jossy  this feature is a grayscale function of CDN product, we consider supporting  it after CDN releases this feature in full. 
I will reply under this question as soon as there is an update of CDN product

**Comment by jossy** [comment]
@gailwang Thanks for your response, I was not aware of the grayscale status. Do you (roughly) know when this functionality will be generally available?

**Comment by gailwang** [comment]
Hi @jossy  The CDN product has no plan for full support in the short term.
