### ISSUE TITLE
tencentcloud_cdn_domain add support for (Origin-Pull) Request Header Configuration

### ISSUE THREAD

**Issue by jossy** [tencentcloudstack/terraform-provider-tencentcloud#558]
Add support for [Request Header Configuration](https://intl.cloud.tencent.com/document/product/228/37037). This could look like the following:

```
request_headers {
  switch = "on"
  header_rules {
    header_mode  = "set"
    header_name  = "X-Example-Header"
    header_value = "example-value"
    rule_type    = "all_content"
  }
}
```

**Comment by gailwang** [comment]
Hi, @jossy We have arranged a special version mainly to solve CDN issue (this request header feature is included),  and it is expected to support in January

**Comment by gailwang** [comment]
@jossy Hi, the latest version(1.53.0) has supported `request_header` parameter. You can have a try with it, see if it meets the needs

**Comment by jossy** [comment]
I can confirm that this works now as expected! :+1: 

```
request_header {
  switch = "on"

  header_rules {
    header_mode  = "set"
    header_name  = "Cdn-Loop"
    header_value = "Tencent"
    rule_type    = "all"
    rule_paths   = ["*"]
  }
}
```
