### ISSUE TITLE
tencentcloud_cdn_domain should not enable "Range GETs Configuration" by default

### ISSUE THREAD

**Issue by jossy** [tencentcloudstack/terraform-provider-tencentcloud#559]
According to the [CDN documentation](https://intl.cloud.tencent.com/document/product/228/7184) "Range GETs" are disabled by default if the origin isn't COS.
However, Terraform switches this setting on when creating a distributions with an external origin.
This is causing a significant negative performance impact when the server doesn't support range requests.

-> "Range GETs" should be off by default for external origins. Ideally, this setting should be configurable via Terraform.

**Comment by gailwang** [comment]
Hi, @jossy We have arranged a special version mainly to solve CDN issue (this range switch feature is included),  and it is expected to support in January

**Comment by gailwang** [comment]
i, the latest version(1.53.0) has supported `range_origin_switch` parameter. You can have a try with it, see if it meets the needs

**Comment by jossy** [comment]
I can confirm that this is working now as expected! :+1:
