### ISSUE TITLE
tencentcloud_cdn_domain add support for Origin-pull timeout configuration

### ISSUE THREAD

**Issue by jossy** [tencentcloudstack/terraform-provider-tencentcloud#574]
The default o[rigin-pull loading timeout](https://intl.cloud.tencent.com/document/product/228/35227) is 10 seconds which in our case is not enough for all our applications.
Could you please add support for this configuration in the Terraform provider?

**Comment by gailwang** [comment]
Hi @jossy
We have received your request and will give a schedule as soon as possible

**Comment by jossy** [comment]
@gailwang Any updates on this?

**Comment by jossy** [comment]
This is now supported via the `origin_pull_timeout` argument.
