### ISSUE TITLE
Add support for VPC peering

### ISSUE THREAD

**Issue by darkelf21cn** [tencentcloudstack/terraform-provider-tencentcloud#586]
Searching "VPC" and "peer" in the document with no luck. Is it currently supported?

**Comment by JustinZ** [comment]
@darkelf21cn  the equivalence of VPC Peering in Tencent Cloud is  CCN . 
The doc is hear:  https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/ccn

**Comment by darkelf21cn** [comment]
@JustinZ Thank you!
