### ISSUE TITLE
mysql import不支持

### ISSUE THREAD

**Issue by comprel** [tencentcloudstack/terraform-provider-tencentcloud#621]
信息：

tencentcloud_mysql_instance.mysql_0033_0000000012: Importing from ID "cdb-dzj24p1f"...

Error: resource tencentcloud_mysql_instance doesn't support import

**Comment by Kagashino** [comment]
Hi @comprel 
The provider was supported to import mysql instance, please upgrade the provider version to `>=1.72.2`.
