### ISSUE TITLE
running_flag不支持停机不收费

### ISSUE THREAD

**Issue by liuliancao** [tencentcloudstack/terraform-provider-tencentcloud#645]
目前只有开机和关机，是否能支持相关设置 支持停机不收费，后者有啥好办法吗

**Comment by Kagashino** [comment]
Hi, 我们在 1.59.18 版本支持了 CVM 停机不收费的配置，尝试在 resource `tencentcloud_instance` 中配置 `stopped_mode="STOP_CHARGING"`，详情参考 [文档](https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/instance#stopped_mode)
