### ISSUE TITLE
MySQL创建增加cpu参数

### ISSUE THREAD

**Issue by BruceBee** [tencentcloudstack/terraform-provider-tencentcloud#647]
目前最新版本中创建MySQL只有mem_size参数，对于相同内存不同cpu的规格创建，无法满足需求。
既有的SDK中已经有了cpu参数，而terraform还没有，期待新版本增加cpu参数，谢谢！

**Comment by hellertang** [comment]
最新版本已经添加，可以试试

**Comment by BruceBee** [comment]
> 最新版本已经添加，可以试试

1.58.1? 没看到cpu参数呢，是不是terraform文档还没更新

**Comment by Kagashino** [comment]
> > 最新版本已经添加，可以试试
> 
> 1.58.1? 没看到cpu参数呢，是不是terraform文档还没更新

1.58.1 版本支持，文档已更新

**Comment by BruceBee** [comment]
点赞~
