### ISSUE TITLE
COS documentation broken in Terraform 1.0.4+

### ISSUE THREAD

**Issue by vwxyzjn** [tencentcloudstack/terraform-provider-tencentcloud#648]
```terraform
resource "tencentcloud_cos_bucket" "mycos" {
  bucket = "mycos-1258798060"

  website = {
    index_document = "index.html"
    error_document = "error.html"
  }
}
```
in the COS documentation no longer works in Terraform 1.0.4+

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/5555347/128601445-24d09867-7e0a-497c-bf43-e6e368f553f7.png">

Instead, the new syntax is 

```terraform
resource "tencentcloud_cos_bucket" "mycos" {
  bucket = "mycos-1258798060"

  website {
    index_document = "index.html"
    error_document = "error.html"
  }
}
```

Please update the documentation correspondingly.

**Comment by hellertang** [comment]
3Q, it has already fixed.
