### ISSUE TITLE
SCF create with layer and image 

### ISSUE THREAD

**Issue by lin051** [tencentcloudstack/terraform-provider-tencentcloud#672]
最新版provider无法创建云函数时使用层管理功能和镜像部署功能

**Comment by hellertang** [comment]
> 最新版provider无法创建云函数时使用层管理功能和镜像部署功能

@lin051 Now, it has supported.
https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/scf_layer
