### ISSUE TITLE
Create VOD Subapplication Resource

### ISSUE THREAD

**Issue by hopuichung** [tencentcloudstack/terraform-provider-tencentcloud#708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We are using `tencentcloud_vod_procedure_template` for creating procedure templates for VOD sub-application. We want to know if any chances to have a terraform resource for creating VOD subapplication so that we can automate the whole setup process.

### New or Affected Resource(s)

* tencentcloud_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by hellertang** [comment]
> ### Community Note
> * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
> * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
> * If you are interested in working on this issue or have submitted a pull request, please leave a comment
> 
> ### Description
> We are using `tencentcloud_vod_procedure_template` for creating procedure templates for VOD sub-application. We want to know if any chances to have a terraform resource for creating VOD subapplication so that we can automate the whole setup process.
> 
> ### New or Affected Resource(s)
> * tencentcloud_XXXXX
> 
> ### Potential Terraform Configuration
> ```terraform
> # Copy-paste your Terraform configurations here - for large Terraform configs,
> # please use a service like Dropbox and share a link to the ZIP file. For
> # security, you can also encrypt the files using our GPG public key.
> ```
> 
> ### References
> * #0

https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/vod_sub_application
