### ISSUE TITLE
terraform init does NOT Work? 

### ISSUE THREAD

**Issue by qiuxin** [tencentcloudstack/terraform-provider-tencentcloud#745]
[root@VM-32-5-centos tencentcloud-instance]# terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/tencentcloud...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/tencentcloud: provider registry
│ registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/tencentcloud
│
│ Did you intend to use tencentcloudstack/tencentcloud? If so, you must specify that source address in each module which
│ requires that provider. To see which modules are currently depending on hashicorp/tencentcloud, run the following command:
│     terraform providers
╵

[root@VM-32-5-centos tencentcloud-instance]# terraform providers

Providers required by configuration:
.
└── provider[registry.terraform.io/hashicorp/tencentcloud]

**Comment by Kagashino** [comment]
What is the provider `hashicorp/tencentcloud` referenced? Our provider source is `tencentcloudstack/tencentcloud`.
Try to specify correct source in required providers: 
```
terraform {
  required_providers {
    tencentcloud = {
      source = "tencentcloudstack/tencentcloud"
    }
  }
}
```

**Comment by qiuxin** [comment]
Appreciate your help. Problem solved.

**Comment by qiuxin** [comment]
BTW, do I need to add the foregoing codes to every main.tf file in the “example” directory？How about putting foregoing codes in the github and avoid the same problem happened again?

**Comment by Kagashino** [comment]
> BTW, do I need to add the foregoing codes to every main.tf file in the “example” directory？How about putting foregoing codes in the github and avoid the same problem happened again?

Thanks for your suggestion, we are planning to add this snippet  to the [provider example usage](https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs#example-usage)  instead of the seperated examples.
