### ISSUE TITLE
How to use system disk only?

### ISSUE THREAD

**Issue by wawajohn** [tencentcloudstack/terraform-provider-tencentcloud#763]
I'm use tencentcloud_instance to create a instance.
But I don't need any more data disks, just only system disk.
What should I do to use system disk only?

**Comment by Kagashino** [comment]
hi @wawajohn 
The `data_disks` is optional argument. No need to declare this argument if you don't need it.

**Comment by wawajohn** [comment]
I haven't declared `data_disks`, but `terraform plan` showd:

      + data_disks {
          + data_disk_id           = (known after apply)
          + data_disk_size         = (known after apply)
          + data_disk_snapshot_id  = (known after apply)
          + data_disk_type         = (known after apply)
          + delete_with_instance   = (known after apply)
          + encrypt                = (known after apply)
          + throughput_performance = (known after apply)
        }

**Comment by Kagashino** [comment]
@wawajohn  the `data_disk` is also a computed arguments, because of the legacy logic - default data disk will automaticlly added after cvm create. So the message of plan just a computed hint, not really create data disks.

**Comment by wawajohn** [comment]
Thank you explain why data_disks showed the message. I tried to apply my plan and it not create data disks, it's work.
