### ISSUE TITLE
SCF 云函数创建失败

### ISSUE THREAD

**Issue by babyzone2004** [tencentcloudstack/terraform-provider-tencentcloud#794]
代码如下：
resource "tencentcloud_scf_function" "foo" {
  name    = "ci-test-function"
  handler = "main.do_it"
  runtime = "Python3.6"
}

执行：terraform apply

提示：“Error: no function code set
│ 
│   with tencentcloud_scf_function.foo,
│   on main.tf line 20, in resource "tencentcloud_scf_function" "foo":
│   20: resource "tencentcloud_scf_function" "foo" {”

**Comment by hellertang** [comment]
创建SCF，至少需要指定代码来源。
可以通过本地ZIP的方式，也可以通过指定cos的方式，也可以通过指定image的方式。

**Comment by babyzone2004** [comment]
已通过zip_file指定代码来源解决
