### ISSUE TITLE
web控制台的cluster_os选择和terraform文档中为何不一致

### ISSUE THREAD

**Issue by huzerun0306** [tencentcloudstack/terraform-provider-tencentcloud#809]
我在tarraform的tke文档中看到这个cluster_os只能选择三种
https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/kubernetes_cluster#cluster_os
我想要使用的是tlinux2.2，但是我无法填写这个，因为他会报错： Msg : OS_NOT_SUPPORT[osName: tlinux2.2x86_64 customizeType GENERAL OS_NOT_SUPPORT]
这个我可以选择忽略，我就用文档中所说的tlinux2.4，但是又报错：Msg : CVM_COMMON_ERROR[InvalidImageId.NotFound:ImageId img-9qabwvbn is not found:7c2f6246-0c5d-46a8-a5ba-b640f2ced663]
我去我的cvm控制台的镜像界面的公共镜像中我发现只存在tlinux2.2，tlinux2.6，tlinux3.2等等，反正没有tlinux2.4，于是我怀疑img-9qabwvbn不存在是因为我这里没有这个tlinux2.4的公共镜像，于是我忽略cluster_os的字段，使用了img_id这个字段填写我的tlinux2.2的镜像id，发现他还是报错一样的不存在img的错误，并且img_id一样，说明它默认还是把cluster_os当作了tlinux2.4，如果这样的话根本无法创建我想要的tke集群了。
有办法解决吗？
我看到相似的问题，不知道是否一致https://github.com/tencentcloudstack/terraform-provider-tencentcloud/issues/199

**Comment by Kagashino** [comment]
As the internal discussion. We have work out the reason:
This issue is only occured in tencentcloud test account. The test account cannot use public images because of the security reason.
Try to use tlinux images which is available for test account.
