### ISSUE TITLE
" Blocks of type "port_limits" are not expected here." in tencentcloud_dayu_ddos_policy API

### ISSUE THREAD

**Issue by qiuxin** [tencentcloudstack/terraform-provider-tencentcloud#831]
Hi There，
I encounter the following error  when I try to test "tencentcloud_dayu_ddos_policy" interface.
link:  https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/dayu_ddos_policy

```
 % terraform apply
╷
│ Error: Unsupported block type
│ 
│   on main.tf line 43, in resource "tencentcloud_dayu_ddos_policy" "test_policy":
│   43:   port_limits {
│ 
│ Blocks of type "port_limits" are not expected here.
```

The problem solved after I delete the following code in the my "main.tf".  
```
  port_limits {
    start_port = "2000"
    end_port   = "2500"
    protocol   = "all"
    action     = "drop"
    kind       = 1
  }
```

**Comment by Kagashino** [comment]
Thanks for your feedback, this block was force changed to `port_filters`. We will fix this example soon.
