### ISSUE TITLE
How to get the latest version of Kubernetes when using the resource `tencentcloud_kubernetes_cluster`

### ISSUE THREAD

**Issue by yuyicai** [tencentcloudstack/terraform-provider-tencentcloud#893]
https://registry.terraform.io/providers/tencentcloudstack/tencentcloud/latest/docs/resources/kubernetes_cluster#cluster_version

The default value of `cluster_version` is `1.10.5`.  
I want to get the latest version by data sources:  
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/13033733/157395708-a00f4ed2-b91a-4ae3-9dbd-8e79a5ba3b82.png">

**Comment by Kagashino** [comment]
Hi @yuyicai 
There is an API `DescribeVersions` can query the version list but our provider haven't support as datasource yet. 
We will consider this impletement if needed.

**Comment by yuyicai** [comment]
> Hi @yuyicai There is an API `DescribeVersions` can query the version list but our provider haven't support as datasource yet. We will consider this impletement if needed.

It is very necessary to get the K8s version from the data source, because the default version is not `latest`  
I can open a pr for this feature

**Comment by Kagashino** [comment]
> > Hi @yuyicai There is an API `DescribeVersions` can query the version list but our provider haven't support as datasource yet. We will consider this impletement if needed.
> 
> It is very necessary to get the K8s version from the data source, because the default version is not `latest` I can open a pr for this feature

Looking forward to your contribution, it is helpful to extending provider feature and improving issue feedback effectiveness.
